/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor_appointment_booking_system;

import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public final class UserLogin extends javax.swing.JFrame {
    
    static Connection con;

    /**
     * Creates new form Login
     */
    public UserLogin() throws SQLException {
        initComponents();
        
        registerBtn.setText("<HTML><U>Register</U></HTML>");
        backgroundImg("C:/Users/Labasan/Documents/NetBeansProjects/blogg.jpg", jLabel1);   
        backgroundImg("C:/Users/Labasan/Documents/NetBeansProjects/close.png", exitBtn);
        
        try{
            con = DBHelper.getConnection();
        } catch(ClassNotFoundException | SQLException ex){}
    }
    
    public void backgroundImg(String icon, JLabel label){
        ImageIcon Myimg = new ImageIcon(icon);
        Image img = Myimg.getImage();
        Image newImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        label.setIcon(image);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(129, 186, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 186, 216), 2));
        jPanel1.setLayout(null);

        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(10, 10, 20, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(870, 0, 40, 40);

        LoginPanel.setBackground(new java.awt.Color(129, 186, 216));
        LoginPanel.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("WeCare Medical");
        LoginPanel.add(jLabel6);
        jLabel6.setBounds(430, 20, 370, 50);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        LoginPanel.add(jLabel3);
        jLabel3.setBounds(30, 130, 100, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        LoginPanel.add(jTextField1);
        jTextField1.setBounds(50, 160, 190, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        LoginPanel.add(jLabel4);
        jLabel4.setBounds(30, 210, 90, 17);
        LoginPanel.add(jPasswordField1);
        jPasswordField1.setBounds(50, 250, 190, 30);

        loginBtn.setBackground(new java.awt.Color(204, 255, 255));
        loginBtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 51, 102));
        loginBtn.setText("LOGIN");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        LoginPanel.add(loginBtn);
        loginBtn.setBounds(90, 320, 100, 40);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("You don't have an account?");
        LoginPanel.add(jLabel5);
        jLabel5.setBounds(20, 420, 180, 30);

        registerBtn.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 0, 51));
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        LoginPanel.add(registerBtn);
        registerBtn.setBounds(200, 420, 70, 30);
        LoginPanel.add(jLabel1);
        jLabel1.setBounds(300, 40, 610, 460);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        LoginPanel.add(jPanel2);
        jPanel2.setBounds(280, -20, 20, 520);

        getContentPane().add(LoginPanel);
        LoginPanel.setBounds(0, 0, 910, 500);

        setSize(new java.awt.Dimension(910, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_registerBtnMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
          boolean result;
        /*
        * Checks if the login is correct or not, if correct it will show the Reservation Layout
        * else a window will popup saying an incorrect username or password
        */
        try{
            String username = jTextField1.getText();
            String password =jPasswordField1.getText();
            
            if(jTextField1.getText().equals("admin")){
                    if(!jTextField1.getText().isEmpty() && jPasswordField1.getPassword().toString().length() > 0){
                        if(jTextField1.getText().equals("admin") && jPasswordField1.getText().equals("123456")){
                            new AdminPage().setVisible(true);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Incorrect Username or Password!");
                        }
                            
                    }else{
                         JOptionPane.showMessageDialog(this, "Fields must not be empty");
                    }
            }else if(!jTextField1.getText().equals("admin")){
                     if(!jTextField1.getText().isEmpty() && jPasswordField1.getPassword().toString().length() > 0){

                    result = new DBHelper().login(username, password);

                    if(!result)
                        JOptionPane.showMessageDialog(this, "Username or Password is incorrect");
                    else{
                        new DBHelper().searchAccount(username, password);
                        this.dispose();
                    }
                
                }
                else
                    JOptionPane.showMessageDialog(this, "Fields must not be empty");
            }
        }catch(Exception ex){            
            ex.printStackTrace();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserLogin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel registerBtn;
    // End of variables declaration//GEN-END:variables
}
